"""Generate app/src/scenes/b9-world.ts: the world map for the Ode to Joy plate.

    uv run python b9_world.py

Natural Earth (public domain, naturalearthdata.com): 1:110m admin-0 countries and 1:50m populated places,
downloaded to analysis/.cache/ne/. Coordinates are quantised to 0.1 degree; Antarctica is left out.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NE = ROOT / "analysis/.cache/ne"


def rings(geom):
    polys = geom["coordinates"] if geom["type"] == "MultiPolygon" else [geom["coordinates"]]
    for poly in polys:
        for ring in poly[:1]:  # outer rings only (the 110m countries have no holes worth drawing)
            yield ring


def main():
    cs = json.loads((NE / "ne_110m_admin_0_countries.geojson").read_text(encoding="utf-8"))
    conts = ["Africa", "Asia", "Europe", "North America", "South America", "Oceania"]
    out_c, npts = [], 0
    for f in cs["features"]:
        p = f["properties"]
        if p["CONTINENT"] in ("Antarctica", "Seven seas (open ocean)"):
            continue
        rs = []
        for r in rings(f["geometry"]):
            q, last = [], None
            for lon, lat in r:
                v = (round(lon * 10), round(lat * 10))
                if v != last:
                    q += v
                    last = v
            if len(q) >= 8:
                rs.append(q)
                npts += len(q) // 2
        out_c.append({"n": p["ADM0_A3"], "c": conts.index(p["CONTINENT"]) if p["CONTINENT"] in conts else 1, "r": rs})
    pl = json.loads((NE / "ne_50m_populated_places_simple.geojson").read_text(encoding="utf-8"))
    cities = []
    for f in pl["features"]:
        p = f["properties"]
        lon, lat = f["geometry"]["coordinates"][:2]
        pop = p.get("pop_max") or 0
        if pop < 50000 or lat < -60:
            continue
        cities.append([round(lon * 10), round(lat * 10), max(1, round(pop / 1000))])
    cities.sort(key=lambda c: -c[2])
    ts = ["// Generated by analysis/b9_world.py from Natural Earth (public domain): 1:110m countries, 1:50m",
          "// populated places. Coordinates in tenths of a degree (lon, lat), Antarctica left out.",
          "/** countries: ISO A3, continent (0 Africa, 1 Asia, 2 Europe, 3 N. America, 4 S. America, 5 Oceania), outer rings as flat [lon, lat, ...] */",
          "export const COUNTRIES: { n: string; c: number; r: number[][] }[] = " + json.dumps(out_c, separators=(",", ":")) + ";",
          "/** cities: [lon, lat, population in thousands], largest first */",
          "export const CITIES: number[][] = " + json.dumps(cities, separators=(",", ":")) + ";", ""]
    dst = ROOT / "app/src/scenes/b9-world.ts"
    dst.write_text("\n".join(ts), encoding="utf-8")
    print(f"{len(out_c)} countries, {npts} points, {len(cities)} cities, {dst.stat().st_size // 1024} KB")


if __name__ == "__main__":
    main()
